### PR TITLE
feat: more languages support info from `linguist-languages`

### LINKED ISSUE #416: Get more language support info from `github/linguist` on build
https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

I'm using this approach for `prettier-plugin-sh` at https://github.com/un-ts/prettier/blob/master/scripts/languages.ts

If you agree, I'd like to raise a PR for it.

### PR DESCRIPTION
**Pull request by JounQin**
close #416

### CODE REVIEW

**Comment by JounQin** [comment]
ping @kddnewton

**Comment by JounQin** [comment]
ping @kddnewton

**Comment by kddnewton** [comment]
👍

**Comment by JounQin** [comment]
@kddnewton Thanks for merging! Shall we release? 😁

**Comment by kddnewton** [comment]
Yup! The new version is released.

**Pull request merged**
